### ISSUE TITLE
stream not found

### ISSUE THREAD

**Issue by kp-emagine** [sonroyaalmerol/m3u-stream-merger-proxy#79] opened 2024-08-18 16:11 UTC
2024/08/18 12:07:33 GetStreams error: stream not found: z - Anthony Bourdain

When accessing /playlist.m3u

/playlist.m3u downloads with only 1 line: `#EXTM3U`

Originating m3u is valid, and contains:
```
#EXTINF:-1 tvg-chno="0.0" tvg-name="z - Anthony Bourdain: No Reservations", z - Anthony Bourdain: No Reservations
http://mystream1`
#EXTINF:-1 tvg-chno="0.0" tvg-name="z - Anthony Bourdain: No Reservations", z - Anthony Bourdain: No Reservations
http://mystream2`
#EXTINF:-1 tvg-chno="0.0" tvg-name="z - Anthony Bourdain: Parts Unknown", z - Anthony Bourdain: Parts Unknown
http://mystream3`
```

**Comment by sonroyaalmerol** [comment] 2024-08-18 17:21
Hi @kp-emagine. This is due to tvg-id not being used by your m3u provider. `0.10.0` probably introduced this regression as it is now being used to sort the channels. Should be fixed by next release.

Since we're here, do you need the `tvg-chno` tag to be parsed as well?

**Comment by kp-emagine** [comment] 2024-08-18 18:44
> Hi @kp-emagine. This is due to tvg-id not being used by your m3u provider. `0.10.0` probably introduced this regression as it is now being used to sort the channels. Should be fixed by next release.
> 
> Since we're here, do you need the `tvg-chno` tag to be parsed as well?

Ahh...   in all honesty... I don't "need" anthing other than the name and stream url ;)   I precurate from my providers since there's so much junk I don't need in the original playlist... generally I tone them down from 200k-300k to 300(ish) lol

**Comment by sonroyaalmerol** [comment] 2024-08-18 21:15
Got ya. I already did some work for this. You can try and test it using the `:dev` image tag.

**Comment by kpirnie** [comment] 2024-08-19 10:31
> Got ya. I already did some work for this. You can try and test it using the `:dev` image tag.

Will give this a shot later on today.  (this is kp-emagine, forgot I was logged in with my work account still lol)

**Comment by kpirnie** [comment] 2024-08-19 13:13
> Got ya. I already did some work for this. You can try and test it using the `:dev` image tag.

seems to work good.

**Comment by aniel300** [comment] 2024-08-19 18:13
@kpirnie where do u get 300k channel from?

**Comment by kpirnie** [comment] 2024-08-19 18:15
> @kpirnie where do u get 300k channel from?
One of my providers.
I dumped one the other day that was sending me over 600k.   Alot of it's VOD stuff

**Comment by aniel300** [comment] 2024-08-19 18:17
ohh wait...when u said 300k channels that was also referring to vod?

**Closed** 2024-08-19 20:52 UTC
Labels: bug
