### ISSUE TITLE
channels are looping/artificing/skipping back in time

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#108] opened 2024-08-24 15:59 UTC
i have this issue where channels are looping/artifacts/skipping back in time. using `BUFFER_MB` i think helps but am not sure. is `BUFFER_MB` on a per global basis or per channel basis. is there anything that can be done in regard to this?

**Comment by kpirnie** [comment] 2024-08-24 19:36
Pretty certain it's a per stream basis

**Comment by sonroyaalmerol** [comment] 2024-08-24 21:09
It is global in a sense that each stream will have the same amount of buffer but per channel/stream has it own separate buffer.

Can you test out #110 and see if it helps? The image url to test should be there as well.

**Comment by aniel300** [comment] 2024-08-25 00:22
ok am testing now with no buffer. if am to test with buffer what is a good size to test?

**Comment by aniel300** [comment] 2024-08-25 02:08
> It is global in a sense that each stream will have the same amount of buffer but per channel/stream has it own separate buffer.
> 
> Can you test out #110 and see if it helps? The image url to test should be there as well.

not sure if it is the provider/ time of the day but it seems more stable now, thank you.

**Comment by aniel300** [comment] 2024-08-25 02:29
issue happened again, can't tell if it better or not. coming back to `BUFFER_MB` is this a buffer from the proxy to the end client or a buffer from the provider to the proxy?

**Comment by kpirnie** [comment] 2024-08-25 02:33
try 64.   thats a 64MB buffer for the merged stream...  

think of it like this...  its basically the amount of data that will fill a "buffer" between the stream and the client watching it.

I worked up to 256 from 16 on my server in increments of 16M.   For my machine, 256 is the sweet spot...  yours may be more, may be less based on your hardware

**Comment by aniel300** [comment] 2024-08-25 02:47
i have tried 2,50,100 and 1000 none seems to make a difference if am not mistaken. i will try ur recommendations though

**Comment by sonroyaalmerol** [comment] 2024-08-25 02:51
#112 might also help with this as a side effect. Both PRs have been merged and released on `0.13.0`.

**Comment by aniel300** [comment] 2024-08-25 02:52
avalible on `;dev` ?

**Comment by aniel300** [comment] 2024-08-25 02:54
also do u guys use buffer at all in ur end? for what it seems now it doesn't make too much different/ can't see it in action between off and on?

**Comment by sonroyaalmerol** [comment] 2024-08-25 02:55
> avalible on `:dev` ?

both `:latest` and `:dev`

**Comment by aniel300** [comment] 2024-08-25 03:20
out of my testing, there is one channel that is freezen yet the proxy was able to recover. wonder if it has to do anything with this cpu spike
![image](https://github.com/user-attachments/assets/b0bb00ae-3603-4a15-9c22-c29a6d96f800)

**Comment by aniel300** [comment] 2024-08-25 03:22
is the buffer held in ram?

**Comment by aniel300** [comment] 2024-08-25 03:31
most related to this:
![image](https://github.com/user-attachments/assets/a69a8628-81ff-4955-ba05-07b750304ca9)

**Comment by aniel300** [comment] 2024-08-25 03:46
some more logs: 

2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Stream ended (EOF reached): xxx:6120
2024/08/24 23:44:42 Retrying same stream until timeout (3 seconds) is reached...
2024/08/24 23:44:42 Timeout reached while trying to stream: xxx:6120
2024/08/24 23:44:42 Exit code 2 received from xxx
2024/08/24 23:44:42 Retrying other servers...
2024/08/24 23:44:42 [DEBUG] Stream attempt 1 out of 0
2024/08/24 23:44:42 Skipping M3U_1: marked as previous stream
2024/08/24 23:44:42 [DEBUG] All streams skipped in lap 0
2024/08/24 23:44:42 [DEBUG] Stream attempt 2 out of 0
2024/08/24 23:44:42 Current number of connections for M3U_1: 3
2024/08/24 23:44:42 Current number of connections for M3U_1: 3
2024/08/24 23:44:46 [DEBUG] Successfully fetched stream from xxx
2024/08/24 23:44:46 Proxying xxx:6120 to xxx
2024/08/24 23:44:46 Current number of connections for M3U_1: 4

**Comment by sonroyaalmerol** [comment] 2024-08-25 05:26
I don't see anything unusual with the logs. The CPU spike is normal and is caused by the recovery process, not the other way around. Yes, buffer is stored in ram but is immediately flushed as soon as the client receives it. Think of it as a queue.

There are too many variables regarding stream reconnects outside of my control (M3U provider connectivity, your own internet connectivity, etc.) which makes it hard for me to answer what is causing your issues. Providers have different ways of handling disconnects. Different M3U clients have different ways of handling reconnects. Those are just a few things you'd want to investigate yourself with your own setup.

Also, is this still related to the main point of this issue? I'm getting a sense that this is already a completely different issue (if it's even an issue or just a general inquiry). If you're not experiencing the issue anymore, feel free to close this one.

I'd like to refrain on discussing multiple issues in one. It makes it hard for people to see which issues are already known.

**Comment by aniel300** [comment] 2024-08-25 05:37
sounds good and it is stable enough as it os for me, thank you once again. closing this for now.

**Comment by sonroyaalmerol** [comment] 2024-08-25 15:16
Your CPU spikes might be related to #116.

**Comment by aniel300** [comment] 2024-08-25 15:24
will test 117 and report back if it is fix or not

**Comment by sonroyaalmerol** [comment] 2024-08-25 18:43
Continuing from #113, I have some questions for me to get a better idea where the problem is.

1. Whenever this "skip back" happens, what are the logs produced by that behavior? I'll only need the logs from the actual "skip back" moment. I want to figure out if this is caused by a retry on the same stream or if it's caused by the proxy moving to another stream as a fallback.
2. If you play the same stream without the proxy, do you experience intermittent connection?
3. Does the "skip back" happen every time it reconnects or is it a random (more or less) occurrence? Any patterns that you've observed might be helpful as well.
4. When it does the "skip back", does the stream continue all the way until it disconnects again?

**Comment by aniel300** [comment] 2024-08-25 19:29
1) ...
2024/08/25 15:07:44 Stream ended (EOF reached): 172.18.0.2:53270
2024/08/25 15:07:44 Retrying same stream until timeout (1 seconds) is reached...
2024/08/25 15:07:44 [DEBUG] Retrying same stream with backoff of 0s...
2024/08/25 15:07:44 Timeout reached while trying to stream: 172.18.0.2:53270
2024/08/25 15:07:44 Exit code 2 received from xxx
2024/08/25 15:07:44 Retrying other servers...
2024/08/25 15:07:44 [DEBUG] Stream attempt 1 out of 0
2024/08/25 15:07:44 Skipping M3U_1: marked as previous stream
2024/08/25 15:07:44 [DEBUG] All streams skipped in lap 0
2024/08/25 15:07:44 [DEBUG] Stream attempt 2 out of 0
2024/08/25 15:07:44 Current number of connections for M3U_1: 1
2024/08/25 15:07:44 Current number of connections for M3U_1: 1
2024/08/25 15:07:44 [DEBUG] Successfully fetched stream from xxx
2024/08/25 15:07:44 Proxying 172.18.0.2:53270 to xxx
2024/08/25 15:07:44 Current number of connections for M3U_1: 2

2) outside of the proxy using vlc on windows the streams get disconnected after x amount of time, x changes base on the time of the day or some other factors cause by the provider and while using the proxy there is the skip backs instead of the disconnect. in addition, i just confirm that the stream is not "stable" anymore by the proxy as it was earlier now. so am not sure if this a time of day, provider throttling, or provider just being a bad provider kind of thing.

3) i think it might be a pattern because now all the streams are "unstable" or at least the 3 am using for debugging this

4) it goes back x amount of time (don't know the exact time) and then it starts looping within that chunk for x amount of time, but sometime there will be an artifact in the stream but continue playing normally. i think it might also do the looping thing, then continue playing and then do the loop again at another point in time/ chunk.

i can try to capture all of this behavior on video and share here or somewhere in case that would help. but if you think this not worth fixing base on the provider being a bad provider, development, debugging and implementation time or if u think this is not fixable base on some kind of limitations, etc I would totally understand and instead i would look for a better provider.

**Comment by kpirnie** [comment] 2024-08-25 21:12
@aniel300 what is your Buffer set to?

**Comment by aniel300** [comment] 2024-08-25 21:16
none. i have try 64 and 256 which doesn't seems to make a difference base on my quick testing

**Comment by sonroyaalmerol** [comment] 2024-08-25 21:39
I'm inclined to say that this is just the provider's server not returning the next chunks of the stream to the proxy. The loop back behavior happens when the proxy requests for the stream again but still receives the same chunk that the provider's server is stuck on.

On the contrary, I think increasing `STREAM_TIMEOUT` to the average number of seconds your provider's stream is usually in a disconnected state whenever it happens. I would say maybe 5-10 seconds? Decreasing the timeout will only result to the proxy closing the current connection and starting a new one only to end up receiving the same data chunk, resulting to your "skip back" issue. However, this does not solve the main cause which is the disconnect issue from your provider and that is something out of my control unfortunately.

**Comment by sonroyaalmerol** [comment] 2024-08-25 23:28
Sorry but I'm not planning on implementing timeouts by ms as it really doesn't make any sense. Lowering the timeout would only cause an issue similar to #116 and would probably look like spam requests to your provider. That's just asking for your connection to be throttled.

**Comment by aniel300** [comment] 2024-08-25 23:39
agree and not a problem. u may close this as i dont know how to do it from my phone.

**Closed** 2024-08-25 23:40 UTC
Labels: bug
