### ISSUE TITLE
Failover No Longer Working (.m3u8 streams)

### ISSUE THREAD

**Issue by kpirnie** [sonroyaalmerol/m3u-stream-merger-proxy#125] opened 2024-08-25 21:26 UTC
## Describe the bug

Failover streams no longer load once the primary stream in the grouping fails.

I can provide an example... where 1 "channel", 3 streams exist and passed to the proxy, only the first is attempted and fails (as expected), but thats it... It is possible this is .m3u8 related.

```
2024/08/25 17:16:47 Received request from 172.20.0.1:47622 for URL: /stream/ei1ldmVyeWJvZHktbG92ZXMtcmF5bW9uZA==.m3u8
2024/08/25 17:16:47 [DEBUG] Stream attempt 1 out of 1
2024/08/25 17:16:47 Current number of connections for M3U_1: 0
2024/08/25 17:16:48 [DEBUG] Successfully fetched stream from http://myprovider/2783157.m3u8
2024/08/25 17:16:48 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-store, no-cache, must-revalidate] Connection:[keep-alive] Content-Type:[application/x-mpegurl] Date:[Sun, 25 Aug 2024 21:16:48 GMT] Server:[nginx]]
2024/08/25 17:16:48 Proxying 172.20.0.1:47622 to http://myprovider/2783157.m3u8
2024/08/25 17:16:48 Current number of connections for M3U_1: 1
2024/08/25 17:16:48 Stream ended (EOF reached): 172.20.0.1:47622
2024/08/25 17:16:48 Retrying same stream until timeout (7 seconds) is reached...
2024/08/25 17:16:48 [DEBUG] Retrying same stream with backoff of 200ms...
2024/08/25 17:16:48 Stream ended (EOF reached): 172.20.0.1:47622
2024/08/25 17:16:48 Retrying same stream until timeout (7 seconds) is reached...
2024/08/25 17:16:48 [DEBUG] Retrying same stream with backoff of 400ms...
2024/08/25 17:16:48 Stream ended (EOF reached): 172.20.0.1:47622
2024/08/25 17:16:48 Retrying same stream until timeout (7 seconds) is reached...
2024/08/25 17:16:48 [DEBUG] Retrying same stream with backoff of 800ms...
2024/08/25 17:16:49 Stream ended (EOF reached): 172.20.0.1:47622
2024/08/25 17:16:49 Retrying same stream until timeout (7 seconds) is reached...
2024/08/25 17:16:49 [DEBUG] Retrying same stream with backoff of 1.6s...
2024/08/25 17:16:51 Stream ended (EOF reached): 172.20.0.1:47622
2024/08/25 17:16:51 Retrying same stream until timeout (7 seconds) is reached...
2024/08/25 17:16:51 [DEBUG] Retrying same stream with backoff of 3.2s...
2024/08/25 17:16:54 Stream ended (EOF reached): 172.20.0.1:47622
2024/08/25 17:16:54 Retrying same stream until timeout (7 seconds) is reached...
2024/08/25 17:16:54 [DEBUG] Retrying same stream with backoff of 6s...
2024/08/25 17:17:00 Timeout reached while trying to stream: 172.20.0.1:47622
2024/08/25 17:17:00 Exit code 2 received from http://myprovider/2783157.m3u8
2024/08/25 17:17:00 Successfully proxied playlist (M3U) file: 172.20.0.1:47622
2024/08/25 17:17:00 Client disconnected: 172.20.0.1:47622
2024/08/25 17:17:00 Current number of connections for M3U_1: 0
```
(*note for me* this is the Everybody Loves Raymond streams)

**Comment by sonroyaalmerol** [comment] 2024-08-25 21:46
I might've seen the cause of this issue when I was doing #124. It was a one line change so I didn't bother creating a separate PR for it. Could you test that image and see if it solves this?

**Comment by kpirnie** [comment] 2024-08-26 00:43
Hey mate, I think you are right.  Wont be able to test until tomorrow though.

Might I suggest checking for .ts streams as well tho?  I pre-curate my m3u's so I know they arent in them, however one of my providers did have a handful or more of them...

**Comment by sonroyaalmerol** [comment] 2024-08-26 01:13
I've set it up so that it's easier to add different types of streams to the exclusion so that shouldn't be a problem if anyone has an issue with a specific type. I'll add them as they go.

**Comment by kpirnie** [comment] 2024-08-26 11:39
Was going to test this morning, but forgot about the caching... quick one for ya... `BASE_URL` would be my local servers serving up the proxied playlist correct?

I'm going to be rebuilding my machine today after an initial test, so not rel sure how much help I can be a little later on...

**Comment by kpirnie** [comment] 2024-08-26 11:43
Ugg... Nope, not working right still.  Now, what's happening is it is skipping to the next channel, instead of the next stream in the requested channel group.

In my example.. I have Expedition X as a 3 stream "channel" after Everybody Loves Raymond's triplet.  Once the first stream in Everybody Loves Raymond fails, it simply skips the other 2 streams and goes right to Expedition X.

**Comment by kpirnie** [comment] 2024-08-26 11:46
Log
```
2024/08/26 07:43:57 Current number of connections for M3U_1: 0
2024/08/26 07:43:58 [DEBUG] Successfully fetched stream from http://myprovider/2783157.m3u8
2024/08/26 07:43:58 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-store, no-cache, must-revalidate] Connection:[keep-alive] Content-Type:[application/x-mpegurl] Date:[Mon, 26 Aug 2024 11:43:58 GMT] Server:[nginx]]
2024/08/26 07:43:58 Proxying 192.168.2.20:55658 to http://myprovider/2783157.m3u8
2024/08/26 07:43:58 Current number of connections for M3U_1: 1
2024/08/26 07:43:58 Stream ended (EOF reached): 192.168.2.20:55658
2024/08/26 07:43:58 Exit code 2 received from http://myprovider/2783157.m3u8
2024/08/26 07:43:58 Successfully proxied playlist: 192.168.2.20:55658
2024/08/26 07:43:58 Client disconnected: 192.168.2.20:55658
2024/08/26 07:43:58 Current number of connections for M3U_1: 0
2024/08/26 07:43:58 Received request from 192.168.2.20:55663 for URL: /stream/ei1ydW5uaW5nLXdpbGQtdy1iZWFyLWdyeWxscw==
2024/08/26 07:43:58 [DEBUG] Stream attempt 1 out of 1
2024/08/26 07:43:58 Current number of connections for M3U_1: 0
2024/08/26 07:43:58 [DEBUG] Successfully fetched stream from http://myprovider/331883
2024/08/26 07:43:58 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-cache] Content-Type:[video/mp2t] Date:[Mon, 26 Aug 2024 11:43:58 GMT] Server:[nginx]]
2024/08/26 07:43:58 Proxying 192.168.2.20:55663 to http://myprovider/331883
2024/08/26 07:43:58 Current number of connections for M3U_1: 1
```

**Comment by kpirnie** [comment] 2024-08-26 15:14
It downloads a .m3u8 file, however, it is 0 bytes and is empty.

**Comment by kpirnie** [comment] 2024-08-26 19:08
> But the source URL straight from the provider downloads a non-empty .m3u8 file, correct?

Yes.  BUT... it's a 302 redirect to another m3u8 filw which downloads.  At the endpoint of that redirect, the Content-Type header is `application/x-mpegurl`

This specific "channel" (everybody loves raymond) has 2 m3u8 streams... both do the 302 redirect, to 2 separate endpoints.  The requested type for both are `vnd.apple.mpegurl` while the Content Type header for both endpoints are the `application/x-mpegurl`

**Comment by sonroyaalmerol** [comment] 2024-08-26 22:15
The redirect itself might not be the issue as the HTTP client of Go follows redirects by default. I made the proxy more "transparent" and now forwards all HTTP headers including `Content-Length` for the m3u8 files. I think it's worth a shot. I've merged the change in the dev build.

**Comment by kpirnie** [comment] 2024-08-26 23:35
hey mate, i'll give it a shot tomorrow ;)  long day today

**Comment by kpirnie** [comment] 2024-08-27 10:39
New error now
```
2024/08/27 06:33:33 Received request from 192.168.2.20:65195 for URL: /stream/z-everybody-loves-raymond.m3u8
2024/08/27 06:33:33 [DEBUG] Stream attempt 1 out of 5
2024/08/27 06:33:33 Current number of connections for M3U_1: 0
2024/08/27 06:33:34 [DEBUG] Successfully fetched stream from http://myprovider/2783157.m3u8
2024/08/27 06:33:34 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-store, no-cache, must-revalidate] Connection:[keep-alive] Content-Length:[1150] Content-Type:[application/x-mpegurl] Date:[Tue, 27 Aug 2024 10:33:34 GMT] Server:[nginx]]
2024/08/27 06:33:34 Proxying 192.168.2.20:65195 to http://myprovider/2783157.m3u8
2024/08/27 06:33:34 Current number of connections for M3U_1: 1
2024/08/27 06:33:34 Stream ended (EOF reached): 192.168.2.20:65195
2024/08/27 06:33:34 Exit code 2 received from http://myprovider/2783157.m3u8
2024/08/27 06:33:34 Successfully proxied playlist: 192.168.2.20:65195
2024/08/27 06:33:34 Client disconnected: 192.168.2.20:65195
2024/08/27 06:33:34 Current number of connections for M3U_1: 0
2024/08/27 06:33:34 Received request from 192.168.2.20:65200 for URL: /stream/HTTP/1.1 200 OK
2024/08/27 06:33:34 Error retrieving stream for slug HTTP/1: stream not found: HTTP/1
2024/08/27 06:33:34 Received request from 192.168.2.20:65201 for URL: /stream/HTTP/1.1 200 OK
2024/08/27 06:33:34 Error retrieving stream for slug HTTP/1: stream not found: HTTP/1
```
And then trying to play `/stream/z-everybody-loves-raymond.m3u8` by itself
```
2024/08/27 06:36:47 Received request from 192.168.2.20:65274 for URL: /stream/z-everybody-loves-raymond.m3u8
2024/08/27 06:36:47 [DEBUG] Stream attempt 1 out of 5
2024/08/27 06:36:47 Current number of connections for M3U_1: 0
2024/08/27 06:36:48 [DEBUG] Successfully fetched stream from http://myprovider/2783157.m3u8
2024/08/27 06:36:48 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-store, no-cache, must-revalidate] Connection:[keep-alive] Content-Length:[1150] Content-Type:[application/x-mpegurl] Date:[Tue, 27 Aug 2024 10:36:48 GMT] Server:[nginx]]
2024/08/27 06:36:48 Proxying 192.168.2.20:65274 to http://myprovider/2783157.m3u8
2024/08/27 06:36:48 Current number of connections for M3U_1: 1
2024/08/27 06:36:48 Stream ended (EOF reached): 192.168.2.20:65274
2024/08/27 06:36:48 Exit code 2 received from http://myprovider/2783157.m3u8
2024/08/27 06:36:48 Successfully proxied playlist: 192.168.2.20:65274
2024/08/27 06:36:48 Client disconnected: 192.168.2.20:65274
2024/08/27 06:36:48 Current number of connections for M3U_1: 0
```
with no other stream attempts.

Do you want me to DM you a m3u with the 3 live streams for this?

**Comment by kpirnie** [comment] 2024-08-27 15:32
This may be something to do with the save to database.... i just noticed on firigin it up, that `[DEBUG] M3U index: 0` for every stream

**Comment by sonroyaalmerol** [comment] 2024-08-27 22:11
> This may be something to do with the save to database.... i just noticed on firigin it up, that [DEBUG] M3U index: 0 for every stream

I don't see anything that would cause this issue from the import process. The `[DEBUG] M3U index: 0` line is logged per stream that is parsed from an M3U playlist and should only be executed during the cronjob or during startup.

I got some clues for the bug in this line:

> 2024/08/27 06:33:34 Received request from 192.168.2.20:65200 for URL: /stream/HTTP/1.1 200 OK

`HTTP/1.1 200 OK` looks like a response from an `OPTIONS` HTTP method request. The proxy only forwarded `GET` requests previously even if the request had a different method. The URL got messed up because the response was for a different request method.

I've changed that behavior and should forward all HTTP method requests accordingly now. Try out the latest dev build and let me know how it goes.

**Comment by kpirnie** [comment] 2024-08-28 10:36
Hey Mate.
Still not getting the next stream in the channel's group.   It's only attempting the first it finds, and then when it errors, it moves to the next channel, instead of the next stream.

Please note, that second channel the proxy goes to actually does work.  I can copy the url in to VLC and watch it.

```
2024/08/28 06:31:50 Received request from 192.168.2.20:62234 for URL: /stream/z-everybody-loves-raymond.m3u8
2024/08/28 06:31:50 [DEBUG] Stream attempt 1 out of 5
2024/08/28 06:31:50 Current number of connections for M3U_1: 0
2024/08/28 06:31:51 [DEBUG] Successfully fetched stream from http://myprovider/2783157.m3u8
2024/08/28 06:31:51 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-store, no-cache, must-revalidate] Connection:[keep-alive] Content-Length:[1151] Content-Type:[application/x-mpegurl] Date:[Wed, 28 Aug 2024 10:31:51 GMT] Server:[nginx]]
2024/08/28 06:31:51 Proxying 192.168.2.20:62234 to http://myprovider/2783157.m3u8
2024/08/28 06:31:51 Exit code 4 received from http://myprovider/2783157.m3u8
2024/08/28 06:31:51 Finished handling GET request: 192.168.2.20:62234
2024/08/28 06:31:51 Client disconnected: 192.168.2.20:62234
2024/08/28 06:31:51 Received request from 192.168.2.20:62240 for URL: /stream/z-expedition-unknown.m3u8
2024/08/28 06:31:51 [DEBUG] Stream attempt 1 out of 5
2024/08/28 06:31:51 Current number of connections for M3U_1: 0
2024/08/28 06:31:53 [DEBUG] Successfully fetched stream from http://myprovider/2783846.m3u8
2024/08/28 06:31:53 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-store, no-cache, must-revalidate] Connection:[keep-alive] Content-Length:[1147] Content-Type:[application/x-mpegurl] Date:[Wed, 28 Aug 2024 10:31:53 GMT] Server:[nginx]]
2024/08/28 06:31:53 Proxying 192.168.2.20:62240 to http://myprovider/2783846.m3u8
2024/08/28 06:31:53 Exit code 4 received from http://myprovider/2783846.m3u8
2024/08/28 06:31:53 Finished handling GET request: 192.168.2.20:62240
2024/08/28 06:31:53 Client disconnected: 192.168.2.20:62240
```

Attempting to play: `/stream/z-everybody-loves-raymond.m3u8`

```
2024/08/28 06:35:09 Received request from 192.168.2.20:62291 for URL: /stream/z-everybody-loves-raymond.m3u8
2024/08/28 06:35:09 [DEBUG] Stream attempt 1 out of 5
2024/08/28 06:35:09 Current number of connections for M3U_1: 0
2024/08/28 06:35:10 [DEBUG] Successfully fetched stream from http://myprovider/2783157.m3u8
2024/08/28 06:35:10 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-store, no-cache, must-revalidate] Connection:[keep-alive] Content-Length:[1151] Content-Type:[application/x-mpegurl] Date:[Wed, 28 Aug 2024 10:35:10 GMT] Server:[nginx]]
2024/08/28 06:35:10 Proxying 192.168.2.20:62291 to http://myprovider/2783157.m3u8
2024/08/28 06:35:10 Exit code 4 received from http://myprovider/2783157.m3u8
2024/08/28 06:35:10 Finished handling GET request: 192.168.2.20:62291
2024/08/28 06:35:10 Client disconnected: 192.168.2.20:62291
```
This channel has 3 streams to it.  It attempts the first, and only the first and then stops.

**Comment by kpirnie** [comment] 2024-08-28 11:41
Hey Mate.
So... done some investigating, and come up with it is the way the data is being stored.  All streams's are not being stored, only the TOP sorted stream is.  This would explain why there is no failover.

```
2024/08/28 07:37:13 Background process: M3U fetching complete. Saving to database...
2024/08/28 07:37:13 [ERROR] Store Array: [0xc000146230 0xc000214e00 0xc0000bc310 0xc0000bc3f0 0xc0000bc540]
2024/08/28 07:37:13 [ERROR] Index: 0
2024/08/28 07:37:13 [ERROR] Value: &{z-blippi z - Blippi 0.0-z - Blippi 0.0   map[0:http://myprovider/2784001.m3u8]}
2024/08/28 07:37:13 [ERROR] Index: 1
2024/08/28 07:37:13 [ERROR] Value: &{z-blue-planet z - Blue Planet 0.0-z - Blue Planet 0.0   map[0:http://myprovider/1356833.m3u8]}
2024/08/28 07:37:13 [ERROR] Index: 2
2024/08/28 07:37:13 [ERROR] Value: &{z-blue-planet-ii z - Blue Planet II 0.0-z - Blue Planet II 0.0   map[0:http://myotherprovider/30691]}
2024/08/28 07:37:13 [ERROR] Index: 3
2024/08/28 07:37:13 [ERROR] Value: &{z-everybody-loves-raymond z - Everybody Loves Raymond 0.0-z - Everybody Loves Raymond 0.0   map[0:http://myprovider/2783157.m3u8]}
2024/08/28 07:37:13 [ERROR] Index: 4
2024/08/28 07:37:13 [ERROR] Value: &{z-expedition-unknown z - Expedition Unknown 0.0-z - Expedition Unknown 0.0   map[0:http://myprovider/2783846.m3u8]}
```

Checked by adding: 
```
log.Printf( "[ERROR] Store Array: %v", storeArray )
		for i, v := range storeArray {
			log.Printf( "[ERROR] Index: %d", i )
			log.Printf( "[ERROR] Value: %v", v )
			
		}
```
Before `SaveToDB` line in `updater.go`

I'll keep digging to see if we can get it to store ALL streams...

**Comment by sonroyaalmerol** [comment] 2024-08-28 17:14
Oh, I think I see what the issue is here. Do you have all streams in one M3U file? If so, then yes, that will be the expected behavior. The proxy expects the failover streams to be on a separate M3U file and each M3U file does not have any duplicate streams within itself. The `M3U_URL_X` naming scheme is what determines which index of the array the URL will be placed in the stream object.

**Comment by kpirnie** [comment] 2024-08-28 17:59
> Oh, I think I see what the issue is here. Do you have all streams including failovers in one M3U file? If so, then yes, that will be the expected behavior. The proxy expects the failover streams to be on a separate M3U file and each M3U file does not have any duplicate streams within itself. The `M3U_URL_X` naming scheme is what determines which index of the array the URL will be placed in the stream object.

Yes, they are all in one.  I have 2 providers, and both send me ... say... Everybody Loves Raymond in multiple streams based on HD, UHD, SD, etc... and even then sometimes I get duplicates not even based on that (see screenshot attached... the top 2 are from the same provider)
![Screenshot_1](https://github.com/user-attachments/assets/1cc109b7-0264-4ba6-8a26-2a3ada1bfdfd)

I rename them so they are all the same (because I dont care if they are SD, HD, etc...), and because these providers are horrible in their nameing schemes...

**Comment by kpirnie** [comment] 2024-08-28 18:03
I have a python script that syncs the remote playlists, runs them through my filters, and then writes a new m3u based on the `TYPE` 

It sets new streams to inactive, but updates existing stream URLs (because, those do change... it's a rare occasion when the ORIG. NAME changes tho...)

I'll have to re-think that "new m3u" writing process then... (ugg)

**Comment by sonroyaalmerol** [comment] 2024-08-28 19:22
The original purpose of the proxy was for me to merge 2 identical M3U files given to me by my provider. Since the connection count was per playlist and not per individual stream, the only way for me to track which stream URL had a free connection was to either brute force test both streams or have a connection counter within the proxy for each playlist.

I might be able to cover your use case if I add an option to disable the counter and just brute force the list of streams. There'll be no point in keeping track of the stream index in that "mode".

**Comment by kpirnie** [comment] 2024-08-29 11:07
> The original purpose of the proxy was for me to merge 2 identical M3U files given to me by my provider. Since the connection count was per playlist and not per individual stream, the only way for me to track which stream URL had a free connection was to either brute force test both streams or have a connection counter within the proxy for each playlist.
> 
> I might be able to cover your use case if I add an option to disable the counter and just brute force the list of streams. There'll be no point in keeping track of the stream index in that "mode".

How many files will it handle?  I'm going to end up with alot... I go from 2 duplicates all the way up to 11 duplicates....

**Comment by sonroyaalmerol** [comment] 2024-08-29 11:12
There is no hard limit set so you should be good

**Comment by kpirnie** [comment] 2024-08-29 11:16
So... I tested with 3 separate M3U files.  All the different streams I have for Everybody Loves Raymond.  None play
```
2024/08/29 07:14:51 [DEBUG] Stream attempt 1 out of 5
2024/08/29 07:14:51 Channel not found from M3U_2: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_1: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_3: z - Everybody Loves Raymond
2024/08/29 07:14:51 [DEBUG] All streams skipped in lap 0
2024/08/29 07:14:51 [DEBUG] Stream attempt 2 out of 5
2024/08/29 07:14:51 Channel not found from M3U_2: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_1: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_3: z - Everybody Loves Raymond
2024/08/29 07:14:51 [DEBUG] All streams skipped in lap 1
2024/08/29 07:14:51 [DEBUG] Stream attempt 3 out of 5
2024/08/29 07:14:51 Channel not found from M3U_2: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_1: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_3: z - Everybody Loves Raymond
2024/08/29 07:14:51 [DEBUG] All streams skipped in lap 2
2024/08/29 07:14:51 [DEBUG] Stream attempt 4 out of 5
2024/08/29 07:14:51 Channel not found from M3U_2: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_1: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_3: z - Everybody Loves Raymond
2024/08/29 07:14:51 [DEBUG] All streams skipped in lap 3
2024/08/29 07:14:51 [DEBUG] Stream attempt 5 out of 5
2024/08/29 07:14:51 Channel not found from M3U_2: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_1: z - Everybody Loves Raymond
2024/08/29 07:14:51 Channel not found from M3U_3: z - Everybody Loves Raymond
2024/08/29 07:14:51 [DEBUG] All streams skipped in lap 4
```
There are 3 files I'm passing... all kp#.m3u with contents like this... just different stream URLs in each
```
#EXTM3U
#EXTINF:-1, z - Everybody Loves Raymond
http://myprovider/1039836.m3u8
```

**Comment by sonroyaalmerol** [comment] 2024-08-29 12:25
I seem to have recreated your problem. I'll investigate and fix it asap

**Comment by sonroyaalmerol** [comment] 2024-08-29 12:33
It should be fixed now on the latest dev. Let me know how it goes :)

**Comment by sonroyaalmerol** [comment] 2024-08-29 13:56
Feel free to try #151. I've confirmed it to be working on the m3u8 streams I tested.

**Comment by kpirnie** [comment] 2024-08-29 19:05
Sorry mate, just getting in to check this out.  I'll have a look and keep ya posted, hopefully shortly

**Comment by kpirnie** [comment] 2024-08-29 19:19
that looks like it did the trick!  it's even failing over now!
friggin wizard ya are ! =)

gonna try it with a full playlist...

**Comment by kpirnie** [comment] 2024-08-29 19:28
Boom! Perfection! =)

**Comment by sonroyaalmerol** [comment] 2024-08-29 20:07
Nice! I'm closing this now as resolved

**Closed** 2024-08-29 20:07 UTC
Labels: bug
